/**
 Notation of music a
 player can read and play.
 */

/// A bar lasts for 4 quarter notes
typealias Bars = UInt

/**
 A Sheet is a ruleset telling
 the player scales to
 play for how long and how.
 
 It consists of a sequence
 of Parts which define
 the generation of a certain
 unpredictable melody with
 a given scale, root and length.

 It is generated by parsing
 a `.compose` file.
 */
struct Sheet {
    let parts: [Part]
    let length: Bars
    
    init(parts: [Part]) {
        self.parts  = parts
        self.length = parts.map{$0.length}.reduce(0, +)
    }
}

/**
 A Part is a definition
 for the generation of
 a melody in a root,
 scale and length in bars.
 */
struct Part {
    let root:   Note
    let scale:  Scale
    let length: Bars
}
